# -*- coding: utf-8 -*-
"""DML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cj0GMXqXZDrNFv8ya77h1RbwWDYwjjPX
"""

import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.model_selection import KFold

# 1. DATA GENERATION (Task 1)
def generate_dml_data(n_samples=1500, n_features=10):
    np.random.seed(42)
    X = np.random.normal(0, 1, (n_samples, n_features))

    # Non-linear propensity score (Treatment Assignment)
    prop_score = 1 / (1 + np.exp(-(X[:, 0] + 0.5 * np.sin(X[:, 1]))))
    T = np.random.binomial(1, prop_score)

    # Non-linear Heterogeneous Treatment Effect (CATE)
    cate = np.maximum(0, X[:, 0]) + (X[:, 1] ** 2)

    # Outcome with non-linear baseline and noise
    baseline = X[:, 2]**2 + np.exp(X[:, 3] * 0.5)
    Y = baseline + T * cate + np.random.normal(0, 0.1, n_samples)

    return X, T, Y, cate

X, T, Y, true_cate = generate_dml_data()
true_ate = np.mean(true_cate)

# 2. DML IMPLEMENTATION WITH CROSS-FITTING (Task 2 & 3)
def perform_dml(X, T, Y, K=5):
    kf = KFold(n_splits=K, shuffle=True, random_state=42)
    tilde_Y = np.zeros(len(Y))
    tilde_T = np.zeros(len(T))

    for train_idx, test_idx in kf.split(X):
        # Nuisance Model 1: E[Y|X]
        model_y = RandomForestRegressor(n_estimators=100, max_depth=5)
        model_y.fit(X[train_idx], Y[train_idx])
        tilde_Y[test_idx] = Y[test_idx] - model_y.predict(X[test_idx])

        # Nuisance Model 2: E[T|X]
        model_t = RandomForestClassifier(n_estimators=100, max_depth=5)
        model_t.fit(X[train_idx], T[train_idx])
        tilde_T[test_idx] = T[test_idx] - model_t.predict_proba(X[test_idx])[:, 1]

    # Orthogonal Moment Estimation
    theta_hat = np.mean(tilde_Y * tilde_T) / np.mean(tilde_T**2)

    # Standard Error Calculation
    residuals = tilde_Y - tilde_T * theta_hat
    se = np.sqrt(np.mean(residuals**2) / (len(Y) * np.mean(tilde_T**2)))

    return theta_hat, se

dml_estimate, dml_se = perform_dml(X, T, Y)

# 3. BASELINE COMPARISON (Task 4)
X_ols = sm.add_constant(np.column_stack((T, X)))
ols_model = sm.OLS(Y, X_ols).fit()